language: php
script: phpunit --coverage-clover=coverage.clover

php:
    - 5.4
    - 5.5
    - 5.6

services: mongodb

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install
    - ./travis/mongo.sh
    - phpenv config-add travis/php.ini
