language: php
script: phpunit

php:
    - 5.4
    - 5.5

services: mongodb

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install
    - ./travis/mongo.sh
    - phpenv config-add travis/php.ini
