language: php
script: phpunit

php:
    - 5.3
    - 5.4
    - 5.5

services: mongodb

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install
    - phpenv config-add myconfig.ini
